[versions]
agp = "8.5.2"
android-compileSdk = "34"
android-minSdk = "23"
android-targetSdk = "34"
compose = "1.7.1"
compose-androidx = "1.7.5"
kotlin = "2.0.21"
ktor = "3.0.1"
maplibre-ios = "6.8.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.9.3" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-androidx" }
kermit = { group = "co.touchlab", name = "kermit", version = "2.0.5" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
maplibre-android = { module = "org.maplibre.gl:android-sdk", version = "11.6.1" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version = "2.8.0-alpha10" }
spatialk-geojson = { group = "io.github.dellisd.spatialk", name = "geojson", version = "0.3.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0-Beta" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jgitver = { id = "fr.brouillard.oss.gradle.jgitver", version = "0.10.0-rc03" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }
mkdocs = { id = "ru.vyarus.mkdocs-build", version = "4.0.1" }
spotless = { id = "com.diffplug.spotless", version = "7.0.0.BETA4" }
