[versions]
androidx-activity = "1.9.3"
androidx-composeUi = "1.7.6"
androidx-navigation = "2.8.0-alpha11"
kermit = "2.0.5"
kotlinx-browser = "0.3"
kotlinx-coroutines = "1.10.1"
ktor = "3.0.3"
maplibre-android-sdk = "11.8.0"
maplibre-android-plugins = "3.0.2"
maplibre-ios = "6.9.0"
maplibre-js = "4.7.1"
spatialk = "0.3.0"
webpack-html = "5.6.3"
webpack-htmlInlineScript = "3.2.1"
webview = "1.9.40"

gradle-android = "8.7.3"
gradle-compose = "1.7.3"
gradle-dokka = "2.0.0"
gradle-jgitver = "0.10.0-rc03"
gradle-kotlin = "2.1.0"
gradle-mavenPublish = "0.30.0"
gradle-mkdocs = "4.0.1"
gradle-spotless = "7.0.1"

tool-prettier = "3.4.2"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-composeUi-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-composeUi" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinx-browser" }
webview = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "webview" }
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
maplibre-android = { module = "org.maplibre.gl:android-sdk", version.ref = "maplibre-android-sdk" }
maplibre-android-scalebar = { module = "org.maplibre.gl:android-plugin-scalebar-v9", version.ref = "maplibre-android-plugins" }
spatialk-geojson = { group = "io.github.dellisd.spatialk", name = "geojson", version.ref = "spatialk" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-android" }
android-library = { id = "com.android.library", version.ref = "gradle-android" }
compose = { id = "org.jetbrains.compose", version.ref = "gradle-compose" }
dokka = { id = "org.jetbrains.dokka", version.ref = "gradle-dokka" }
jgitver = { id = "fr.brouillard.oss.gradle.jgitver", version.ref = "gradle-jgitver" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "gradle-kotlin" }
kotlin-composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "gradle-kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "gradle-kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "gradle-kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "gradle-mavenPublish" }
mkdocs = { id = "ru.vyarus.mkdocs-build", version.ref = "gradle-mkdocs" }
spotless = { id = "com.diffplug.spotless", version.ref = "gradle-spotless" }
