---
name: "CI"

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  check-format:
    runs-on: "ubuntu-latest"
    permissions:
      checks: write
      issues: write
      pull-requests: write
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: "./gradlew spotlessApply"
      - if: "${{ github.event_name == 'pull_request' }}"
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: spotless
          cleanup: false
      - run: "git diff --exit-code"

  check-podspec:
    runs-on: "macos-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: "./gradlew podInstall"
      - run: |
          git diff -I '^COCOAPODS: [0-9]+\.[0-9]+\.[0-9]+$' --exit-code

  lint-android:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: "./gradlew lint"

  test-android:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        api-level:
          - 24
          - 35
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - name: "Run with AVD ./gradlew connectedDebugAndroidTest"
        uses: "./.github/actions/run-with-avd"
        with:
          api-level: "${{ matrix.api-level }}"
          script: "./gradlew connectedDebugAndroidTest"

  test-ios:
    runs-on: "macos-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: "./gradlew iosSimulatorArm64Test"

  build-docs:
    runs-on: "macos-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: "./gradlew generateDocs"
      - uses: "actions/upload-pages-artifact@v3"
        with:
          path: "build/docs"

  build-android-app:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: "./gradlew packageDebug"
      - uses: "actions/upload-artifact@v4"
        with:
          if-no-files-found: "error"
          name: "demo-app-debug"
          path: "demo-app/build/outputs/apk/debug/demo-app-debug.apk"

  all-good:
    needs:
      - "check-format"
      - "check-podspec"
      - "lint-android"
      - "test-android"
      - "test-ios"
      - "build-docs"
      - "build-android-app"
    runs-on: "ubuntu-latest"
    steps:
      - run: "echo 'All checks passed!'"
